# Generated by Django 4.0.2 on 2022-04-07 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
